local L = LibStub('AceLocale-3.0'):NewLocale(..., 'ruRU')
if not L then
    return
end
-- Translator ZamestoTV
-- @locale:language=ruRU@
L = L or {}
L["Add advance rule"] = "Добавить расширенное правило"
L["Add rule"] = "Добавить правило"
L["Advancee rules use ItemSearchModify-1.3"] = "Расширенные правила используют ItemSearchModify-1.3"
L["Already exists"] = "Уже существует"
L["Are you sure |cffff191919DELETE|r rule and its |cffff1919SUBRULES|r?"] = "Вы уверены, что хотите |cffff191919УДАЛИТЬ|r правило и его |cffff1919ПОДПРАВИЛА|r?"
L["Are you sure |cffff191919DELETE|r rule?"] = "Вы уверены, что хотите |cffff191919УДАЛИТЬ|r правило?"
L["Are you sure to |cffff1919RESET|r rules?"] = "Вы уверены, что хотите |cffff1919СБРОСИТЬ|r правила?"
L["Are you sure you want to restore the current Settings?"] = "Вы уверены, что хотите восстановить текущие настройки?"
L["Bag"] = "Сумка"
L["Bank"] = "Банк"
L["Bank and bag stacking together"] = "Сумка и банк складываются вместе"
L["Buttons"] = "Кнопки"
L["Character Specific Settings"] = "Настройки для конкретного персонажа"
L["COMMENT_CLASS"] = "Классовые предметы"
L["Drag to modify the sorting order"] = "Перетащите, чтобы изменить порядок сортировки"
L["Edit rule"] = "Редактировать правило"
L["Enable chat message"] = "Включить сообщения в чате"
L["Enjoy!"] = "Наслаждайтесь!"
L["Help"] = "Помощь"
L["ITEM_TAG: Cloth"] = "Ткань"
L["ITEM_TAG: Cooking"] = "Кулинария"
L["ITEM_TAG: Elemental"] = "Стихии"
L["ITEM_TAG: Enchanting"] = "Зачарование"
L["ITEM_TAG: Herb"] = "Трава"
L["ITEM_TAG: Jewelry"] = "Ювелирные изделия"
L["ITEM_TAG: Leather"] = "Кожа"
L["ITEM_TAG: Metal & Stone"] = "Металл и камень"
L["ITEM_TAG: Mount"] = "Маунт"
L["ITEM_TAG: Pet"] = "Питомец"
L["Keep bank items stack full"] = "Держать стопки предметов в банке полными"
L["KEYWORD_CLASS"] = "Классы"
L["Leave bank, pack cancel."] = "Покинуть банк, упаковка отменена."
L["Left Click"] = "ЛКМ"
L["Name (Optional)"] = "Имя (опционально)"
L["None"] = "Ничего"
L["OPEN_OPTIONS"] = "Открыть настройки"
L["OPEN_RULE_OPTIONS"] = "Открыть настройки правил"
L["Pack canceled."] = "Упаковка отменена."
L["Pack finish."] = "Упаковка завершена."
L["Player enter combat, pack cancel."] = "Игрок вступил в бой, упаковка отменена."
L["Player in combat"] = "Игрок в бою"
L["Player is dead"] = "Игрок мертв"
L["Please drop the item, money or skills."] = "Пожалуйста, выбросите предмет, деньги или навыки."
L["Profile"] = "Профиль"
L["Put in an item to add simple rule"] = "Поместите предмет, чтобы добавить простое правило"
L["Put where?"] = "Куда положить?"
L["Reset rule"] = "Сбросить правило"
L["Restore default Settings"] = "Восстановить настройки по умолчанию"
L["Reverse pack"] = "Обратная упаковка"
L["Right Click"] = "ПКМ"
L["Root"] = "Корень"
L["Rule"] = "Правило"
L["Rules"] = "Правила"
L["Rules restore to default."] = "Правила восстановлены по умолчанию."
L["SAVE"] = "Сохранить в банк"
L["Save to bank when default packing"] = "Сохранять в банк при стандартной упаковке"
L["SAVING_DESC"] = "Сохранять предметы в банк."
L["SAVING_NAME"] = "Сохранение"
L["Select an icon (Optional)"] = "Выберите иконку (опционально)"
L["Some slot is locked"] = "Некоторые слоты заблокированы"
L["SORT"] = "Упаковка по умолчанию"
L["SORT_ASC"] = "Сортировать по возрастанию"
L["SORT_BAG"] = "Сортировать сумку"
L["SORT_BAG_ASC"] = "Сортировать сумку по возрастанию"
L["SORT_BAG_DESC"] = "Сортировать сумку по убыванию"
L["SORT_BANK"] = "Сортировать банк"
L["SORT_BANK_ASC"] = "Сортировать банк по возрастанию"
L["SORT_BANK_DESC"] = "Сортировать банк по убыванию"
L["SORT_DESC"] = "Сортировать по убыванию"
L["SORTING_DESC"] = "Сортировать сумки и банк."
L["SORTING_NAME"] = "Сортировка"
L["Tools"] = "Инструменты"
L["Transporter"] = "Транспортер"
L["UPDATE_RULES_CONFIRM"] = [=[Текущая версия tdPack2 обновляет большое количество правил. Хотите сбросить правила на настройки по умолчанию?
Помощь в выборе:
1. Я знаю, о чем этот запрос: выберите самостоятельно
2. Я не знаю, как выбрать: Принять
]=]
L["Usuable"] = "Используемый"
